### ISSUE TITLE
Top of graph is cut off when values are specified as strings

### ISSUE THREAD

**Issue by sarah-clements** [metricsgraphics/metrics-graphics#841] opened 2018-03-29 23:50 UTC
This only happens if I use data with two decimals. The highest value for this example is 22.00. Is there a work-around for this?

![screen shot 2018-03-29 at 4 31 48 pm](https://user-images.githubusercontent.com/19615783/38118514-fa575e7c-336f-11e8-8418-0b0b6aa579cf.png)

**Comment by wlach** [comment] 2018-03-30 14:42
This just sounds like a bug, maybe in the axis scaling code? If you have time to look into it, we've fixed a bunch of similar things recently if you look at the commit log. Otherwise I can try to find some time to take a peek next week.

**Comment by wlach** [comment] 2018-03-30 14:43
btw, a reproducible test case on jsfiddle using the latest version would be helpful, see for example #838

**Comment by sarah-clements** [comment] 2018-03-30 18:50
Here's a [fiddle](https://jsfiddle.net/sclements/n5u2wwjg/1997/) showing the problem.

**Comment by wlach** [comment] 2018-04-04 13:57
The problem here seems to be that you're specifying the values as strings, if I change the value `"20.0"` in your example to `20.0` the axis seems to scale as expected;

https://jsfiddle.net/n5u2wwjg/7372/

That said, we should fix the axis scaling code to accept values passed in as strings (probably by trying to coerce them into numbers).

**Comment by sarah-clements** [comment] 2018-04-04 17:06
It does, but if you remove the "" from all of the values in the fiddle, the labels display the numbers as integers - not decimals. Interestingly, here's another [example](https://jsfiddle.net/n5u2wwjg/7749/) where the values are represented as either numbers or strings. If you change one number to be an outlier, say 10.72, the values represented as strings show decimals correctly and the values represented as numbers are rounded. 

Either way, I don't think there's a work-around to using a method like .toFixed() to display decimals when using division (which returns a string).

**Comment by wlach** [comment] 2018-04-04 17:30
You might coincidentally get the behavior you expect some of the time with strings and that function, it depends on what you pass in. In the first example you posted, "8.72" resolves to be greater than "20.0" (as a string), so it gets classified as the maximum.

It doesn't surprise me to hear that there are some issues with formatting values for display on the legend. Please file bugs for what you see and we can try to address them (@openjck has been filing some issues for some similar things, so maybe check there for problems first).

**Comment by sarah-clements** [comment] 2018-04-04 17:44
Sure, I can file another bug. To be clear: you think the labels showing numbers being incorrectly rounded is unrelated to this original problem, which is the result of strings - rather than numbers - being provided (and the workaround in the meantime is not to use strings)?

**Comment by wlach** [comment] 2018-04-04 17:48
@sarah-clements I'm pretty sure that these are two seperate problems, yeah. #843 should fix the axis scaling issues when strings are passed in.

**Comment by sarah-clements** [comment] 2018-04-04 17:50
Ok, thanks for looking into this!

**Comment by openjck** [comment] 2018-04-04 20:33
Is this related to #823?

**Comment by wlach** [comment] 2018-04-04 20:43
@openjck no that looks different, as we're seeing that bug when the values are specified as integers.

**Comment by wlach** [comment] 2018-04-09 14:27
Ok, after discussing this with @hamilton and @sarah-clements, I think what we really want is to fix #844 -- that was the motivation for using strings instead of numbers in the first place. Closing this one.

**Closed by wlach** 2018-04-09 14:27 UTC
Labels: bug
